### ISSUE TITLE
About syscalls

### ISSUE THREAD

**Issue by utcq** [austanss/skylight#13] opened 2024-02-03 07:58 UTC
Ii'm trying to use skylight as a base for my os,but i was wondering how could i implement a fopen syscall, trying to read a pointer from userspace to kernel space (path string) obviously makes the kernel crash, so how can i read/translate user memory addresses to kernel?
here's my code:
```c
void fopen(vfs_handle_t* out, char* path, vfs_open_flags_t flags) {
    task_context_t* ctx = ((gs_kernel_base_t*)(rdmsr(IA32_GS_BASE)))->ctx;
    uint64_t pid = ((gs_kernel_base_t*)(rdmsr(IA32_GS_BASE)))->pid;
    paging_table_t* kpml4 = paging_get_pml4();
    paging_load_pml4((paging_table_t *)ctx->cr3);

    serial_print_quiet(path);

    paging_load_pml4(kpml4);
}
```
when trying to print the path in serial the kernel just goes into unknown exception (obviously it can't find the value referred by the pointer).

**Comment by austanss** [comment] 2024-02-03 12:03
Well, your syscall handler boilerplate for context switching works great, so I applaud you for that.

Memory addresses that originate from a user program may or may not be mapped in the kernel's page table. If the virtual address provided corresponds with the actual physical address it is mapped to, then it would likely work, as I believe that the kernel maps all of the usable memory regions with their physical addresses. 

However, user programs can opt to map their pages largely wherever they want in their own virtual address space, so after you load the user program's page tables for manipulation with `paging_load_pml4` then you can use `paging_walk_page` to find the physical memory address of the path provided. However, it is not guaranteed that this address is mapped in the kernel's virtual address space, so either map it yourself or make sure it is already mapped.

**Comment by austanss** [comment] 2024-02-03 15:12
However, in the larger context of creating an `fopen` function, as of commit [`d601b23`](https://github.com/austanss/skylight/commit/d601b239a24552a69bbb713d75ffbf4d19e76baa) you will need to create your own filesystem and disk driver as during the time this is written there is no implementation in the kernel or in user-space currently. You will also need to change the `syscall` handler code to add your syscall function into the table and adjust the system-call count.

**Comment by utcq** [comment] 2024-02-03 18:41
thank you for your response, i will try using `paging_walk_page`, i have my tar-like initramfs archive format from my old os so i was trying to implement that.

**Comment by utcq** [comment] 2024-02-03 18:44
btw, i can automatically map the addr in the fopen function (in user space), i tried this workaround but isn't really working as the buffer is empty in kernel memory:
```c
void fopen(vfs_handle_t* out, char* path, vfs_open_flags_t flags) { // user space 
    kvmap(path);
    sfopen(out, path, flags);
}
```

kvmap is a new syscall here's the source:
```c
void kvmap(void* virt) { // kernel syscall
    if (!virt) {
        return;
    }

    void* phys = paging_walk_page(virt);
    paging_unmap_page(virt);
    paging_map_page(virt, phys, PAGING_FLAGS_KERNEL_PAGE);
    return;
}
```
while using physical mapping shows buffer as: `D���h���t�������\�������������������������������������������P���`
if you could explain how i should map the pointer i would really appreciate that

**Comment by austanss** [comment] 2024-02-03 23:27
You shouldn't unmap the virtual page of the path, as that serves no purpose if it isn't mapped and a detrimental purpose if it is. As for the rest of the code, I hope the code you provided is not the actual code in its full implementation; the boilerplate code I applauded you for is extremely essential in the task as if you do not load the kernel PML4 into the page editor then the walking and mapping is pointless.

However, I have reason to suspect a design flaw in the page editor code surrounding context switches and that this scenario is a possible stressor. I'll investigate further into this later to see if this may be the case.

**Comment by utcq** [comment] 2024-02-04 00:03
yeah, i realized that i shouldn't unmap the virtual address but even without unmapping the code isn't working i tried every type of mapping, i tried phys from user to kernel, virt from user to kernel, phys to virt, virt to phys even double mapping (user and kernel) but the buffer is still empty

**Comment by austanss** [comment] 2024-02-18 17:20
I've investigated the issue, and realized that the design of the page-table manager is not well equipped to deal with context switches and system calls. While I have labored to make this design fit with counterintuitive workarounds and half-measures, I've resolved that it will take an effort on my part to redesign the page-table manager to better fit context switching and user-space execution.

For the features that you are intending to implement, my intended changes will help to facilitate them more effectively. I am not sure if you can complete your intended task without these changes, as the design flaws manifest themselves in undefined behavior and buggy quirks. 

As I have identified the cause of the issue, I will close this issue. I am afraid that I cannot provide you with a very direct resolution to the issue you put forth. Yet, if it's worth your effort, I'm confident in your abilities to intuit and push through these obstacles if you have enough perseverance. Or you can wait, but... I wouldn't rely on me if I were you.

**Closed as not planned** 2024-05-14 20:35 UTC
Labels: deeprunning, impactful, ub
